/*USER POST AND GROUP POST IN SAME TABLE*/
CREATE TABLE IF NOT EXISTS posts (
  id UUID NOT NULL PRIMARY KEY,
  number BIGSERIAL NOT NULL,
  active BOOLEAN NOT NULL,
  created_on TIMESTAMP NOT NULL,
  updated_on TIMESTAMP NOT NULL,
  type POST_TYPE NOT NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT NOT NULL,
  keyword TEXT,
  visibility VISIBILITY NOT NULL,
  group UUID FOREIGN KEY REFERENCES groups(id) NOT NULL,
  user UUID FOREIGN KEY REFERENCES specials(id) NOT NULL,
  approved BOOLEAN NOT NULL
) ;