CREATE TABLE IF NOT EXISTS notifications (
  id UUID NOT NULL PRIMARY KEY,
  number BIGSERIAL NOT NULL,
  active BOOLEAN NOT NULL,
  created_on TIMESTAMP NOT NULL,
  updated_on TIMESTAMP NOT NULL,
  event UUID FOREIGN KEY REFERENCES events(id) NOT NULL,
  sender UUID FOREIGN KEY REFERENCES users(id) NOT NULL,
  recipient UUID FOREIGN KEY REFERENCES users(id) NOT NULL,
  message TEXT NOT NULL,
  seen BOOLEAN NOT NULL
) ;